development:
  adapter: postgresql
  database: gallery_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: gallery_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: gallery_production
  pool: 5
  timeout: 5000